//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertType
    {
        public AlertType()
        {
            this.Coupon_Alert = new HashSet<Coupon_Alert>();
        }
    
        public int Id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Coupon_Alert> Coupon_Alert { get; set; }
    }
}
