//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class couponEntities2 : DbContext
    {
        public couponEntities2()
            : base("name=couponEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlertType> AlertTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Costumer> Costumers { get; set; }
        public virtual DbSet<Coupon_Alert> Coupon_Alert { get; set; }
        public virtual DbSet<Coupon_Order> Coupon_Order { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Coupons_Social_Cupon> Coupons_Social_Cupon { get; set; }
        public virtual DbSet<Firm_Owner> Firm_Owner { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<SocialNetworkProfile> SocialNetworkProfiles { get; set; }
        public virtual DbSet<Sytem_Admin> Sytem_Admin { get; set; }
        public virtual DbSet<User_Prefrences> User_Prefrences { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersCoupon_Alert> UsersCoupon_Alert { get; set; }
    }
}
