//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costumer
    {
        public Costumer()
        {
            this.User_Prefrences = new HashSet<User_Prefrences>();
            this.Coupon_Order = new HashSet<Coupon_Order>();
        }
    
        public int Id { get; set; }
        public int gender { get; set; }
        public double age { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
    
        public virtual User User { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual ICollection<User_Prefrences> User_Prefrences { get; set; }
        public virtual ICollection<Coupon_Order> Coupon_Order { get; set; }
    }
}
