//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon_Order
    {
        public Coupon_Order()
        {
            this.Costumers = new HashSet<Costumer>();
        }
    
        public int Id { get; set; }
        public int coupon_id { get; set; }
        public System.DateTime date { get; set; }
        public string recepit { get; set; }
        public bool isUsed { get; set; }
        public string creditApproval { get; set; }
        public double rank { get; set; }
        public string rankDesc { get; set; }
        public string qrForOrder { get; set; }
        public double serialKey { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual ICollection<Costumer> Costumers { get; set; }
    }
}
