//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sytem_Admin
    {
        public Sytem_Admin()
        {
            this.Firm_Owner = new HashSet<Firm_Owner>();
            this.Firms = new HashSet<Firm>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Firm_Owner> Firm_Owner { get; set; }
        public virtual ICollection<Firm> Firms { get; set; }
        public virtual User User { get; set; }
    }
}
